### ISSUE TITLE
Great work - Can I help to test the SG8K-D?

### ISSUE THREAD

**Issue by highground88** [ttvt/ModbusTCP2MQTT#1]
Much appreciated your work on this - out of my skill level! But can I help to assist in testing this out on my newly acquired SG8K-D so it too is supported? I assume it is the same/similar to the 5. Mine has the wifi module (v31) attached.

**Comment by ttvt** [comment]
Sure.
I've add suport for SG8KD based on SG3KD. Feel free to test it

**Comment by highground88** [comment]
Thanks very much! Unfortunately I can't seem to connect though - this is the log:

```
[services.d] starting services
[services.d] done.
WARNING:root:Modbus connection failed
[cmd] /run.sh exited 0
```

Config:
```
 
inverter_ip
192.168.20.85
 
inverter_port
502
 
slave
1
 
model
sungrow-sg8kd
 
timeout
3
 
scan_interval
10
 
mqtt_server
192.168.0.6
 
mqtt_port
1883
 
mqtt_topic
inverter/stats
 
mqtt_username
mqtt
 
mqtt_password
••••

```

I can ping the inverter from the HA machine ok. Do you have any suggestions? Cheers

**Comment by highground88** [comment]
Just an update - I managed to get it to become stable - I have no idea how, but perhaps I'll leave my config below. Of note, I'm using the SG5KD on my 8kw, as it appears to be more complete than the SG8KD that you created (thanks! - logs in previous messages).

I will also past my configuration.yaml entry at the bottom if it perhaps helps you / someone else. This was made in a way that the new energy features in HA will recognise them, and can therefore be used in the new Energy tab. So far I think it works...

 ### CONFIG for TCPModbus Solar Inverter
```
inverter_ip
192.168.x.x
 
inverter_port
502
 
slave
1
 
model
sungrow-sg5kd
 
timeout
60
 
scan_interval
30
 
mqtt_server
192.168.x.x
 
mqtt_port
1883
 
mqtt_topic
inverter/stats
 
mqtt_username
mqtt
 
mqtt_password
xxxx
```

### HOME ASSISTANT configuration.yaml entries
```
 sensor: 

  - platform: mqtt
    name: "Daily Power Production"
    state_topic: inverter/stats
    value_template: "{{ value_json.daily_power_yield /1000 }}"
    unit_of_measurement: 'kWh'
    unique_id: 394857362700
    state_class: total_increasing
    device_class: energy

  - platform: mqtt
    name: "Total Power Yield"
    state_topic: inverter/stats
    value_template: "{{ value_json.total_power_yield }}"
    unit_of_measurement: 'MWh'
    state_class: total_increasing
    device_class: energy
    unique_id: 394857362708

  - platform: mqtt
    name: "Internal Temperature"
    state_topic: inverter/stats
    unit_of_measurement: '°C'
    value_template: "{{ value_json.internal_temp }}"
    unique_id: 394857360728

  - platform: mqtt
    name: "pv1_voltage"
    state_topic: inverter/stats
    value_template: "{{ value_json.pv1_voltage }}"
    unit_of_measurement: 'V'
    unique_id: 394057362728

  - platform: mqtt
    name: "pv1_current"
    state_topic: inverter/stats
    value_template: "{{ value_json.pv1_current }}"
    unit_of_measurement: 'A'
    unique_id: 394857399928

  - platform: mqtt
    name: "pv2_voltage"
    state_topic: inverter/stats
    value_template: "{{ value_json.pv2_voltage }}"
    unit_of_measurement: 'V'
    unique_id: 388857362728

  - platform: mqtt
    name: "pv2_current"
    state_topic: inverter/stats
    value_template: "{{ value_json.pv2_current }}" 
    unit_of_measurement: 'A'
    unique_id: 394877762728

  - platform: mqtt
    name: "total_pv_power"
    state_topic: inverter/stats
    value_template: "{{ value_json.total_pv_power }}"
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    unique_id: 394856662728

  - platform: mqtt
    name: "grid_voltage"
    state_topic: inverter/stats
    value_template: "{{ value_json.grid_voltage }}"
    unit_of_measurement: 'V'
    unique_id: 394855562728

  - platform: mqtt
    name: "inverter_current"
    state_topic: inverter/stats
    value_template: "{{ value_json.inverter_current }}" 
    unit_of_measurement: 'A'
    unique_id: 394844442728

  - platform: mqtt
    name: "export_power"
    state_topic: inverter/stats
    value_template: "{{ value_json.export_power }}"
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement    
    unique_id: 394857362711

  - platform: mqtt
    name: "export_power_indicator"
    state_topic: inverter/stats
    value_template: "{{ value_json.export_power_indicator }}"
    unique_id: 3929957362728

  - platform: mqtt
    name: "power_meter"
    state_topic: inverter/stats
    value_template: "{{ value_json.power_meter }}" 
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    unique_id: 394853672728

  - platform: mqtt
    name: "daily_purchased_energy"
    state_topic: inverter/stats
    value_template: "{{ value_json.daily_purchased_energy }}"
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
   # last_reset: "2021-08-05T08:05:00+00:00"
    unique_id: 394857362528

  - platform: mqtt
    name: "daily_energy_consumption"
    state_topic: inverter/stats
    value_template: "{{ value_json.daily_energy_consumption /1000 }}"
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    unique_id: 394237362728

  - platform: mqtt
    name: "total_energy_consumption_from_pv"
    state_topic: inverter/stats
    value_template: "{{ value_json.total_energy_consumption }}" 
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy    
    unique_id: 394857336728
    
  - platform: mqtt
    name: "calculated_solar_feed_in" 
    state_topic: inverter/stats    
    unit_of_measurement: 'kWh'
    value_template: "{{ states('sensor.daily_power_yield') |float - states('sensor.daily_energy_consumption') | round(1) | float }}"
    unique_id: 394117419721
    state_class: total_increasing
    device_class: energy     
 
  - platform: mqtt
    name: "export_power_negative"
    state_topic: inverter/stats
    value_template: "{{ states('sensor.export_power') |float*(-1) }}"   
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement    
    unique_id: 394144362811 
    
  - platform: template
    sensors:
     calculated_solar_feed_in_rounded:
       unit_of_measurement: 'kWh'
       value_template: "{{ states('sensor.calculated_solar_feed_in') | round(1) | float }}"
       unique_id: 394447419721
```
